import type { Item } from '@/api/Item'

export const links: Item[] = [
  {
    title: '我的博客',
    color: '#FF1493',
    url: 'https://chensina.cn',
    icon: 'fa-blog',
    pinyin: 'blog',
  },
  {
    title: '飞牛NAS',
    color: '#b95fb7',
    url: 'https://nas.chensina.cn:5667',
    icon: 'server',
    pinyin: 'feiniunas',
  },
  {
    title: '飞牛影音',
    color: '#20B2AA',
    url: 'https://nas.chensina.cn:5667/v',
    icon: 'fa-film',
    pinyin: 'feiniuyingyin',
  },

  {
    title: 'NasTool',
    color: '#EE82EE',
    url: 'http://192.168.1.105:3002/',
    icon: 'fa-cog',
    pinyin: 'nastool',
  },
  {
    title: 'QBittorrent',
    color: '#d3573f',
    url: 'http://192.168.1.250:8085/',
    icon: 'fa-circle-down',
    pinyin: 'qbittorrent',
  },
  {
    title: 'PVE',
    color: 'Green',
    url: 'https://pve.chensina.cn',
    icon: 'server',
    pinyin: 'pve',
  },
  {
    title: 'TP主路由',
    color: '#2F4F4F',
    url: 'http://192.168.1.1',
    icon: 'satellite-dish',
    pinyin: 'tpzhuluyou',
  },
  {
    title: 'iKuai',
    color: '#8968CD',
    url: 'http://192.168.1.80',
    icon: 'wifi',
    pinyin: 'ikuai',
  },
  {
    title: 'V2raya',
    color: '#2465ED',
    url: 'http://192.168.1.80:2017',
    icon: 'fa-regular fa-paper-plane',
    pinyin: 'v2raya',
  },

  {
    title: 'Zerotier组网',
    color: '#00BFFF',
    url: 'https://zerotierchensina.cn',
    icon: 'wifi',
    pinyin: 'zerotierzuwang',
  },
  {
    title: 'Docker文档',
    color: '#BDB76B',
    url: 'https://chensina.cn:4000',
    icon: 'fa-brands fa-docker ',
    pinyin: 'dockerwendang',
  },
  {
    title: 'ElementPlus文档',
    color: '#DAA520',
    url: 'https://chensina.cn:2028',
    icon: 'fa-book',
    pinyin: 'elementpluswendang',
  },
  {
    title: 'JavaGuide',
    color: '#CD5C5C',
    url: 'https://javaguide.cn/home.html',
    icon: 'fa-java fa-brands',
    pinyin: 'javaguide',
  },
  {
    title: '小林Coding',
    color: '#ABCDAC',
    url: 'https://www.xiaolincoding.com/',
    icon: 'fa-java fa-brands',
    pinyin: 'xiaolincoding',
  },
  // {
  //   title: '任务管理',
  //   color: '#FA8072',
  //   url: 'https://ddns.chensina.cn:2036',
  //   icon: 'list-ol',
  //   pinyin: 'renwuguanlidootask',
  // },
  {
    title: 'Kuma',
    color: '#6A5ACD',
    url: 'https://chensina.cn:2026',
    icon: 'fa-brands fa-watchman-monitoring',
    pinyin: 'kuma',
  },
  {
    title: '数据备份',
    color: '#483D8B',
    url: 'http://192.168.1.105:2703/',
    icon: 'microchip',
    pinyin: 'goback',
  },
  {
    title: 'Jenkins',
    color: '#7B68EE',
    url: 'http://192.168.1.105:2031/',
    icon: 'fa-jenkins fa-brands',
    pinyin: 'jenkins',
  },
  {
    title: 'ELK',
    color: '#8A2BE2',
    url: 'http://192.168.1.105:5601/',
    icon: 'search',
    pinyin: 'elasticlogstashkibana',
  },
  {
    title: 'Minio',
    color: '#00CED1',
    url: 'https://ddns.chensina.cn:2033/',
    icon: 'hdd',
    pinyin: 'minio',
  },
  {
    title: '惠耐美后台',
    color: '#9400D3',
    url: 'https://huinaimei.chensina.cn:8888/',
    icon: 'person-digging',
    pinyin: 'huinaimeihoutai',
  },
  {
    title: 'yudao商城',
    color: '#5F9EA0',
    url: 'https://huinaimei.chensina.cn:2035/',
    icon: 'cart-shopping',
    pinyin: 'yudaoshangcheng',
  },
  {
    title: '长亭雷池',
    color: '#8B008B',
    url: 'https://ddns.chensina.cn:9443/',
    icon: 'microchip',
    pinyin: 'changtingleichi',
  },
  {
    title: 'CodeCV简历',
    color: '#DA70D6',
    url: 'http://192.168.1.105:8080',
    icon: 'microchip',
    pinyin: 'codecvjianli',
  },
  {
    title: 'SSL证书部署',
    color: '#1E90FF',
    url: 'http://192.168.1.105:7979',
    icon: 'fa-brands fa-expeditedssl',
    pinyin: 'sslzhengshu',
  },
]
